// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfpgkutptnsgtskuethh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmcGdrdXRwdG5zZ3Rza3VldGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3OTY0NDUsImV4cCI6MjA5MTM3MjQ0NX0.egni0Jo66DEYc9KvUPq-HaUtIjBefpzoivmgftUoVM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});